-d D:\t-fpga projects\simple-esp32-fpga-digital-adder\adder\impl\gwsynthesis\adder.vg
-p GW1NSR-4C-QFN48P-6
-pn GW1NSR-LV4CQN48PC6/I5
-cst D:\t-fpga projects\simple-esp32-fpga-digital-adder\adder\src\adder.cst
-cfg D:\t-fpga projects\simple-esp32-fpga-digital-adder\adder\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
